export const ROW_LABEL_WIDTH = 70;
export const ROW_INPUT_WIDTH = 260;
export const ROW_GAP = 8;
export const ROW_GROUP_WIDTH = ROW_INPUT_WIDTH * 2 + ROW_GAP;
export const VALUE_INPUT_WIDTH = 100;
export const PROTOBUF_FIELD_ID_WIDTH = 90;
export const PROTOBUF_TYPE_WIDTH = 140;
export const PROTOBUF_COLUMN_WIDTH =
  ROW_GROUP_WIDTH - PROTOBUF_FIELD_ID_WIDTH - PROTOBUF_TYPE_WIDTH - ROW_GAP * 2;
export const EXPORT_DURATION_WIDTH =
  ROW_GROUP_WIDTH - VALUE_INPUT_WIDTH * 2 - ROW_GAP * 2;
